export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENT = "SET_INGREDIENT";
export const FETCH_INGREDIENT_FAILED = "FETCH_INGREDIENT_FAILED";

export const CREATE_ORDER = "CREATE_ORDER";
export const CREATE_ORDER_FAILED = "CREATE_ORDER_FAILED";
export const PURCHASE_BURGER_START = "PURCHASE_BURGER_START";
export const PURCHASE_INIT = "PURCHASE_INIT";

export const SET_ORDERS_START = "SET_ORDERS_START";
export const SET_ORDERS = "SET_ORDERS";
export const SET_ORDERS_FAILED = "SET_ORDERS_FAILED";

export const AUTHENTICATION_START = "AUTHENTICATION_START";
export const AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED";
export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS";
